behaviors:
  RRC:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 102400
      learning_rate: 0.001
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 15000000
    time_horizon: 1000
    summary_freq: 50000
